# Base configs
baseurl: "https://bendypics.github.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Max Bender"
subtitle: "See the world through my eyes!"
author: "Max Bender"
header:
 title: "Photography"
 subtitle: "by Max Bender"
footer:
 name: "Hey there, my name is Max"
 bio: ""
 github: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/mbender4242"
  instagram: "https://www.instagram.com/bendypics"
  linkedin: "https://www.linkedin.com/in/maxwellbender/"
  github: "https://www.github.com/maxbender"
